"""
Django settings for devtrack project.

Generated by 'django-admin startproject' using Django 6.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kq1!rq1sr8fngntsvj4+g44@z6xv8r6=a#cqjqj3hj9^9&6zy-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Folder holding database of json files
DATABASE_DIR = BASE_DIR / 'database'

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'issues',
]

MIDDLEWARE = [
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'devtrack.urls'

WSGI_APPLICATION = 'devtrack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {}

REST_FRAMEWORK = {
    # No authentication, every endpoint is open
    'DEFAULT_AUTHENTICATION_CLASSES' : [],
    'DEFAULT_PERMISSION_CLASSES' : [
        'rest_framework.permissions.AllowAny',
    ],

    # Without django.contrib.auth installed, request.user must not be built
    'UNAUTHENTICATED_USER' : None,

    # JSON only. The browsalbe API renderer needs templates, which is removed
    'DEFAULT_RENDERER_CLASSES' : [
        'rest_framework.renderes.JSONRenderer',
    ],

    'DEFAULT_PARSER_CLASSES' : [
        'rest_framework.parsers.JsonParser',
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


DEFAULT_AUTO_FILED = 'django.db.models.BigAutoField'
